### ISSUE TITLE
Can't run GPT With CPU getting an error

### ISSUE THREAD

**Issue by DFanso** [TorRient/localGPT-falcon#3]
this is the error im getting can u help me to fix it,
<pre>root@beast:~/localGPT-falcon# python run_localGPT.py --device_type cpu
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn(&quot;The installed version of bitsandbytes was compiled without GPU support. &quot;
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Running on: cpu
load INSTRUCTOR_Transformer
max_seq_length  512
Using embedded DuckDB with persistence: data will be stored in: /root/localGPT-falcon/DB
Traceback (most recent call last):
  File &quot;/root/localGPT-falcon/run_localGPT.py&quot;, line 103, in &lt;module&gt;
    main()
  File &quot;/usr/lib/python3/dist-packages/click/core.py&quot;, line 1128, in __call__
    return self.main(*args, **kwargs)
  File &quot;/usr/lib/python3/dist-packages/click/core.py&quot;, line 1053, in main
    rv = self.invoke(ctx)
  File &quot;/usr/lib/python3/dist-packages/click/core.py&quot;, line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File &quot;/usr/lib/python3/dist-packages/click/core.py&quot;, line 754, in invoke
    return __callback(*args, **kwargs)
  File &quot;/root/localGPT-falcon/run_localGPT.py&quot;, line 76, in main
    llm = load_model()
  File &quot;/root/localGPT-falcon/run_localGPT.py&quot;, line 22, in load_model
    pipe = pipeline(
  File &quot;/usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py&quot;, line 788, in pipeline
    framework, model = infer_framework_load_model(
  File &quot;/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py&quot;, line 278, in infer_framework_load_model
    raise ValueError(f&quot;Could not load model {model} with any of the following classes: {class_tuple}.&quot;)
ValueError: Could not load model tiiuae/falcon-7b-instruct with any of the following classes: (&lt;class &apos;transformers.models.auto.modeling_auto.AutoModelForCausalLM&apos;&gt;,).</pre>

**Comment by TorRient** [comment]
@DFanso
I fixed that, please pull the latest code.
Tks!

**Comment by DFanso** [comment]
thank you bro

**Comment by DFanso** [comment]
this time after few minutes its saying killed. 
[https://cdn.discordapp.com/attachments/1129689826019512410/1134085969293881344/image.png](url)

**Comment by TorRient** [comment]
@DFanso Out of memory. It takes about 30-36Gb memory when you run on CPU.

**Comment by DFanso** [comment]
okay bro 🥹

**Comment by DFanso** [comment]
ram or storage

**Comment by TorRient** [comment]
RAM bro :D

**Comment by DFanso** [comment]
nice  🥲

**Comment by TorRient** [comment]
@DFanso I have a suggestion for you: you can try out LoRA (Low-Rank Adaptation) models to increase speed and reduce memory usage. Currently, I don't have the time to do that.

**Comment by DFanso** [comment]
hey bro we added more rams and now its 219gb. but getting a new error. https://cdn.discordapp.com/attachments/1129689826019512410/1134147676775129249/image.png

**Comment by TorRient** [comment]
@DFanso It's just a warning, you can ignore it. The model run on CPU may take you a few minutes to answer. If possible, please use GPU on Colab, it only takes a few seconds to answer 1 question

**Comment by DFanso** [comment]
we are using a server. Poweredge R750xs , with  4310 intel Xeon, can you hlep us to fix this, how to ignore that warning and use it. if you have discord send me your discord

**Comment by TorRient** [comment]
I mean it's no error, you just have to wait until the model returns the result.
Discord: username - torrient
