### ISSUE TITLE
Getting error when i run this on cpu

### ISSUE THREAD

**Issue by harshpp707** [TorRient/localGPT-falcon#4]
![image](https://github.com/TorRient/localGPT-falcon/assets/73919744/f352fe18-08cb-46fe-91e7-430415408939)

**Comment by TorRient** [comment]
It could be an issue related to the version of Pandas library you are currently using. Please try installing Pandas version 2.0.3.

`pip install pandas==2.0.3`

**Comment by harshpp707** [comment]
Yes i was able to fix this by downgrading pandas to version 1.5.3.
Thank you
