### ISSUE TITLE
all files are not read

### ISSUE THREAD

**Issue by harshpp707** [TorRient/localGPT-falcon#5]
This does not read the documents inside another directory? For example in SOURCE_Documents folder i have another folder which contains files. It does not read that. Is it intended to do it that way?

**Comment by TorRient** [comment]
Yes, the current code does not support your use-case, you can make modifications here.
https://github.com/TorRient/localGPT-falcon/blob/main/ingest.py?plain=1#L24

**Comment by harshpp707** [comment]
got it thank you
