### ISSUE TITLE
Listen on 0.0.0.0?

### ISSUE THREAD

**Issue by DocMAX** [TorRient/localGPT-falcon#8]
Sorry, not an issue but a question.
How can i make it listen to 0.0.0.0:7860?

**Comment by TorRient** [comment]
@DocMAX 
oh, config server_name="0.0.0.0"
demo.launch(share=share, server_name="0.0.0.0")
https://github.com/TorRient/localGPT-falcon/blob/main/app.py#L300

**Comment by DocMAX** [comment]
Ah thanks, found my own solution:

GRADIO_SERVER_NAME=0.0.0.0 python3 app.py
